#:schema node_modules/wrangler/config-schema.json
name = "api"
main = "src/api.ts"
compatibility_date = "2024-11-06"
compatibility_flags = ["nodejs_compat"]

[dev]
port = 8080

[[d1_databases]]
binding = "DB"
database_name = "<<name>>"
database_id = "<<id>>"